<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f4dc8a9dc436',
	'title' => 'Items Banner',
	'fields' => array(
		array(
			'key' => 'field_5f7ceb64a027e',
			'label' => '',
			'name' => 'banner_option',
			'type' => 'radio',
			'instructions' => 'Opción Banner',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Imagen' => 'Imagen',
				'Vídeo' => 'Vídeo',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'Imagen',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5f4dc8aab07b7',
			'label' => '',
			'name' => 'banner_image',
			'type' => 'image',
			'instructions' => 'Imagen',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7ceb64a027e',
						'operator' => '==',
						'value' => 'Imagen',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f7cebf4a027f',
			'label' => '',
			'name' => 'banner_video',
			'type' => 'file',
			'instructions' => 'Vídeo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7ceb64a027e',
						'operator' => '==',
						'value' => 'Vídeo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f4dc8aab0b5f',
			'label' => '',
			'name' => 'banner_title',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4dc8aab0f2b',
			'label' => '',
			'name' => 'banner_subtitle',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4dc8aab1303',
			'label' => '',
			'name' => 'banner_description',
			'type' => 'text',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4dcaa0312fa',
			'label' => '',
			'name' => 'banner_button',
			'type' => 'text',
			'instructions' => 'Botón',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4dcab2312fb',
			'label' => '',
			'name' => 'banner_urlbutton',
			'type' => 'text',
			'instructions' => 'Url Botón',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'itemsbanner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5f3a6ab755cac',
	'title' => 'Items Vídeo',
	'fields' => array(
		array(
			'key' => 'field_5f3a6ac05c546',
			'label' => '',
			'name' => 'image_items_video',
			'type' => 'image',
			'instructions' => 'Imagen Poster',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f3a6b365c549',
			'label' => '',
			'name' => 'option_items_video',
			'type' => 'radio',
			'instructions' => 'Opción Vídeo',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Url' => 'Url',
				'Upload' => 'Upload',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5f3a6ae45c547',
			'label' => '',
			'name' => 'video_items_video',
			'type' => 'file',
			'instructions' => 'Upload Vídeo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a6b365c549',
						'operator' => '==',
						'value' => 'Upload',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f3a6b125c548',
			'label' => '',
			'name' => 'url_video_items_video',
			'type' => 'text',
			'instructions' => 'Url Vídeo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a6b365c549',
						'operator' => '==',
						'value' => 'Url',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'itemsvideo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5f4470fe65ec6',
	'title' => 'Template Clever',
	'fields' => array(
		array(
			'key' => 'field_5f44711527892',
			'label' => '',
			'name' => 'template_clever',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Página General' => 'Página General',
				'Catálogo' => 'Catálogo',
				'Contacto' => 'Contacto',
				'Shop' => 'Shop',
				'Ninguno' => 'Ninguno',
			),
			'default_value' => 'Ninguno',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f44715e27893',
			'label' => 'Página General',
			'name' => 'title-banner-general-page',
			'type' => 'text',
			'instructions' => 'Título Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Página General',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f44719227894',
			'label' => '',
			'name' => 'subtitle-banner-general-page',
			'type' => 'text',
			'instructions' => 'Subtítulo Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Página General',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4472e127897',
			'label' => '',
			'name' => 'image-banner-general-page',
			'type' => 'image',
			'instructions' => 'Imagen Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'General Page',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f447492b993a',
			'label' => 'Catálogo',
			'name' => 'title-banner-catalogo',
			'type' => 'text',
			'instructions' => 'Título Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Catálogo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4479ad829be',
			'label' => '',
			'name' => 'subtitle-banner-catalogo',
			'type' => 'text',
			'instructions' => 'Subtítulo Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Catálogo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4475796b10d',
			'label' => '',
			'name' => 'image-banner-catalogo',
			'type' => 'image',
			'instructions' => 'Imagen Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Catálogo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f4482d8b1ea7',
			'label' => 'Contacto',
			'name' => 'title-contacto',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4488a7e7f10',
			'label' => '',
			'name' => 'map-contacto',
			'type' => 'textarea',
			'instructions' => 'Map',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f44834cb1ea8',
			'label' => 'Distribuidor',
			'name' => 'title-distribuidor',
			'type' => 'text',
			'instructions' => 'Título Distribuidor',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4483aeb1ea9',
			'label' => '',
			'name' => 'subtitle-distribuidor',
			'type' => 'text',
			'instructions' => 'Subtítulo Distribuidor',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4483e1b1eaa',
			'label' => '',
			'name' => 'title-national-distribuidor',
			'type' => 'text',
			'instructions' => 'Título Nacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f44840bb1eab',
			'label' => '',
			'name' => 'image-national-distribuidor',
			'type' => 'image',
			'instructions' => 'Imagen Distribuidor Nacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f448437b1eac',
			'label' => '',
			'name' => 'phone-national-distribuidor',
			'type' => 'text',
			'instructions' => 'Teléfono Nacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f448473b1ead',
			'label' => '',
			'name' => 'whatsapp-national-distribuidor',
			'type' => 'text',
			'instructions' => 'Whatsapp Nacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f44848ab1eae',
			'label' => '',
			'name' => 'email-national-distribuidor',
			'type' => 'email',
			'instructions' => 'Email Nacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5f4484c7b1eaf',
			'label' => '',
			'name' => 'title-international-distribuidor',
			'type' => 'text',
			'instructions' => 'Título Internacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4484e9b1eb0',
			'label' => '',
			'name' => 'image-international-distribuidor',
			'type' => 'image',
			'instructions' => 'Imagen Distribuidor Internacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f448507b1eb1',
			'label' => '',
			'name' => 'phone-international-distribuidor',
			'type' => 'text',
			'instructions' => 'Teléfono Internacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f448526b1eb2',
			'label' => '',
			'name' => 'whatsapp-international-distribuidor',
			'type' => 'text',
			'instructions' => 'Whatsapp Iternacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f44853db1eb3',
			'label' => '',
			'name' => 'email-international-distribuidor',
			'type' => 'email',
			'instructions' => 'Email Internacional',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f44711527892',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>